/**
 * VARIANT — SIEM (Security Information and Event Management) Service
 *
 * Centralized log aggregation, correlation, and alerting.
 * This is the backbone of blue-team/SOC analyst training.
 *
 * What it does:
 *   - Aggregates logs from all machines in the simulation
 *   - Correlates events across sources
 *   - Evaluates alert rules against the log stream
 *   - Supports custom detection rules (level designer writes them)
 *   - Timeline reconstruction for forensic investigation
 *   - Dashboard data generation for the Defense lens
 *   - Severity-based alerting with configurable thresholds
 *
 * EXTENSIBILITY:
 *   - Custom alert rule registry (third-party)
 *   - Custom log parsers (third-party)
 *   - Custom correlation rules
 *   - Export formats (CEF, LEEF, JSON)
 *
 * SECURITY: All rules are declarative. No code execution.
 * The SIEM engine operates on immutable log entries.
 */

// ── SIEM Types ─────────────────────────────────────────────────

/**
 * A structured log entry from any source.
 */
export interface SIEMLogEntry {
    readonly id: string;
    readonly timestamp: number;
    readonly tick: number;
    readonly source: SIEMLogSource;
    readonly severity: SIEMSeverity;
    readonly category: string;
    readonly message: string;
    readonly raw: string;
    /** Structured fields extracted from the log. */
    readonly fields: Readonly<Record<string, string | number | boolean>>;
    /** tags for filtering. */
    readonly tags: readonly string[];
}

export interface SIEMLogSource {
    readonly machine: string;
    readonly service: string;
    readonly logFile: string;
}

export type SIEMSeverity = 'debug' | 'info' | 'notice' | 'warning' | 'error' | 'critical' | 'alert' | 'emergency';

/**
 * An alert generated by a detection rule.
 */
export interface SIEMAlert {
    readonly id: string;
    readonly ruleId: string;
    readonly ruleName: string;
    readonly severity: SIEMSeverity;
    readonly timestamp: number;
    readonly tick: number;
    readonly description: string;
    /** Log entries that triggered this alert. */
    readonly evidence: readonly SIEMLogEntry[];
    /** MITRE ATT&CK technique ID (if applicable). */
    readonly mitreTechnique?: string;
    /** Whether the alert has been acknowledged by the player. */
    readonly acknowledged: boolean;
    /** Player notes. */
    readonly notes: string;
    /** False positive flag. */
    readonly falsePositive: boolean;
}

// ── Detection Rules ────────────────────────────────────────────

/**
 * A detection rule that generates alerts from log patterns.
 * Declarative — no code execution.
 */
export interface SIEMDetectionRule {
    readonly id: string;
    readonly name: string;
    readonly description: string;
    readonly severity: SIEMSeverity;
    /** MITRE ATT&CK technique (for enrichment). */
    readonly mitreTechnique?: string;
    /** Rule conditions. ALL must match for the rule to fire. */
    readonly conditions: readonly SIEMRuleCondition[];
    /** Minimum occurrences within the window to trigger. */
    readonly threshold: number;
    /** Time window in ticks. */
    readonly windowTicks: number;
    /** Cooldown after firing (prevent alert storm). */
    readonly cooldownTicks: number;
    /** Whether this rule is enabled. */
    readonly enabled: boolean;
}

export type SIEMRuleCondition =
    | { readonly type: 'field-equals'; readonly field: string; readonly value: string | number | boolean }
    | { readonly type: 'field-contains'; readonly field: string; readonly substring: string }
    | { readonly type: 'field-regex'; readonly field: string; readonly pattern: string }
    | { readonly type: 'message-contains'; readonly substring: string }
    | { readonly type: 'message-regex'; readonly pattern: string }
    | { readonly type: 'severity-gte'; readonly minSeverity: SIEMSeverity }
    | { readonly type: 'source-machine'; readonly machine: string }
    | { readonly type: 'source-service'; readonly service: string }
    | { readonly type: 'category-equals'; readonly category: string }
    | { readonly type: 'tag-present'; readonly tag: string };

// ── Correlation Rules ──────────────────────────────────────────

/**
 * Multi-event correlation. Detects patterns across multiple
 * events from different sources.
 */
export interface SIEMCorrelationRule {
    readonly id: string;
    readonly name: string;
    readonly description: string;
    readonly severity: SIEMSeverity;
    readonly mitreTechnique?: string;
    /** Event patterns that must ALL occur within the window. */
    readonly patterns: readonly SIEMCorrelationPattern[];
    /** Time window in ticks. */
    readonly windowTicks: number;
    readonly cooldownTicks: number;
    readonly enabled: boolean;
}

export interface SIEMCorrelationPattern {
    readonly label: string;
    readonly conditions: readonly SIEMRuleCondition[];
    /** Ordering constraint relative to other patterns. */
    readonly after?: string;
}

// ── SIEM Engine ────────────────────────────────────────────────

/**
 * The SIEM engine. One per simulation.
 */
export interface SIEMEngine {
    /** Ingest a log entry. */
    ingest(entry: SIEMLogEntry): void;
    /** Ingest a batch of log entries. */
    ingestBatch(entries: readonly SIEMLogEntry[]): void;
    /** Advance the tick (evaluates rules). */
    tick(currentTick: number): readonly SIEMAlert[];
    /** Query logs by filter. */
    query(filter: SIEMQuery): readonly SIEMLogEntry[];
    /** Get all alerts. */
    getAlerts(): readonly SIEMAlert[];
    /** Get unacknowledged alerts. */
    getPendingAlerts(): readonly SIEMAlert[];
    /** Acknowledge an alert by ID. */
    acknowledgeAlert(alertId: string): boolean;
    /** Mark an alert as false positive. */
    markFalsePositive(alertId: string): boolean;
    /** Add a note to an alert. */
    addAlertNote(alertId: string, note: string): boolean;
    /** Add a detection rule dynamically. */
    addRule(rule: SIEMDetectionRule): void;
    /** Remove a detection rule. */
    removeRule(ruleId: string): boolean;
    /** Add a correlation rule. */
    addCorrelationRule(rule: SIEMCorrelationRule): void;
    /** Get all rules (detection + correlation). */
    getRules(): readonly SIEMDetectionRule[];
    /** Get all correlation rules. */
    getCorrelationRules(): readonly SIEMCorrelationRule[];
    /** Get log count by severity. */
    getStats(): SIEMStats;
    /** Reconstruct a timeline between two ticks. */
    timeline(fromTick: number, toTick: number): readonly SIEMLogEntry[];
    /** Get total log count. */
    logCount(): number;
    /** Export logs in a specific format. */
    export(format: 'json' | 'cef' | 'csv'): string;
}

export interface SIEMQuery {
    readonly source?: { machine?: string; service?: string; logFile?: string };
    readonly severity?: SIEMSeverity;
    readonly fromTick?: number;
    readonly toTick?: number;
    readonly category?: string;
    readonly messageContains?: string;
    readonly fieldEquals?: Readonly<Record<string, string | number | boolean>>;
    readonly tags?: readonly string[];
    readonly limit?: number;
}

export interface SIEMStats {
    readonly totalLogs: number;
    readonly totalAlerts: number;
    readonly pendingAlerts: number;
    readonly bySeverity: Readonly<Record<SIEMSeverity, number>>;
    readonly byMachine: Readonly<Record<string, number>>;
    readonly byService: Readonly<Record<string, number>>;
    readonly rulesActive: number;
    readonly correlationRulesActive: number;
}

// ── Severity Ordering ──────────────────────────────────────────

const SEVERITY_ORDER: Record<SIEMSeverity, number> = {
    debug: 0,
    info: 1,
    notice: 2,
    warning: 3,
    error: 4,
    critical: 5,
    alert: 6,
    emergency: 7,
};

function severityGte(a: SIEMSeverity, b: SIEMSeverity): boolean {
    return SEVERITY_ORDER[a] >= SEVERITY_ORDER[b];
}

// ── Factory ────────────────────────────────────────────────────

/**
 * Create a SIEM engine.
 */
export function createSIEMEngine(
    maxLogSize: number = 100_000,
): SIEMEngine {
    const logs: SIEMLogEntry[] = [];
    const alerts: SIEMAlert[] = [];
    const detectionRules: SIEMDetectionRule[] = [];
    const correlationRules: SIEMCorrelationRule[] = [];
    const ruleCooldowns = new Map<string, number>();
    let currentTick = 0;
    let nextAlertId = 1;

    function matchesCondition(entry: SIEMLogEntry, condition: SIEMRuleCondition): boolean {
        switch (condition.type) {
            case 'field-equals':
                return entry.fields[condition.field] === condition.value;
            case 'field-contains': {
                const val = entry.fields[condition.field];
                return typeof val === 'string' && val.includes(condition.substring);
            }
            case 'field-regex': {
                const val = entry.fields[condition.field];
                if (typeof val !== 'string') return false;
                try {
                    return new RegExp(condition.pattern).test(val);
                } catch {
                    return false;
                }
            }
            case 'message-contains':
                return entry.message.includes(condition.substring);
            case 'message-regex':
                try {
                    return new RegExp(condition.pattern).test(entry.message);
                } catch {
                    return false;
                }
            case 'severity-gte':
                return severityGte(entry.severity, condition.minSeverity);
            case 'source-machine':
                return entry.source.machine === condition.machine;
            case 'source-service':
                return entry.source.service === condition.service;
            case 'category-equals':
                return entry.category === condition.category;
            case 'tag-present':
                return entry.tags.includes(condition.tag);
        }
    }

    function matchesAllConditions(entry: SIEMLogEntry, conditions: readonly SIEMRuleCondition[]): boolean {
        return conditions.every(c => matchesCondition(entry, c));
    }

    function evaluateDetectionRules(_newEntries: readonly SIEMLogEntry[]): SIEMAlert[] {
        const newAlerts: SIEMAlert[] = [];

        for (const rule of detectionRules) {
            if (!rule.enabled) continue;

            // Check cooldown
            const cooldownUntil = ruleCooldowns.get(rule.id);
            if (cooldownUntil !== undefined && currentTick < cooldownUntil) continue;

            // Find matching entries within the window
            const windowStart = currentTick - rule.windowTicks;
            const matching = logs.filter(entry =>
                entry.tick >= windowStart &&
                matchesAllConditions(entry, rule.conditions),
            );

            if (matching.length >= rule.threshold) {
                const alert: SIEMAlert = {
                    id: `alert-${nextAlertId++}`,
                    ruleId: rule.id,
                    ruleName: rule.name,
                    severity: rule.severity,
                    timestamp: Date.now(),
                    tick: currentTick,
                    description: rule.description,
                    evidence: Object.freeze(matching.slice(-10)), // Last 10 matches
                    ...(rule.mitreTechnique !== undefined ? { mitreTechnique: rule.mitreTechnique } : {}),
                    acknowledged: false,
                    notes: '',
                    falsePositive: false,
                };

                newAlerts.push(alert);
                alerts.push(alert);

                // Set cooldown
                if (rule.cooldownTicks > 0) {
                    ruleCooldowns.set(rule.id, currentTick + rule.cooldownTicks);
                }
            }
        }

        return newAlerts;
    }

    function evaluateCorrelationRules(): SIEMAlert[] {
        const newAlerts: SIEMAlert[] = [];

        for (const rule of correlationRules) {
            if (!rule.enabled) continue;

            const cooldownUntil = ruleCooldowns.get(rule.id);
            if (cooldownUntil !== undefined && currentTick < cooldownUntil) continue;

            const windowStart = currentTick - rule.windowTicks;
            const windowLogs = logs.filter(e => e.tick >= windowStart);

            // Check all patterns match
            const patternMatches = new Map<string, SIEMLogEntry[]>();
            let allMatch = true;

            for (const pattern of rule.patterns) {
                const matching = windowLogs.filter(e => matchesAllConditions(e, pattern.conditions));
                if (matching.length === 0) {
                    allMatch = false;
                    break;
                }
                patternMatches.set(pattern.label, matching);
            }

            if (!allMatch) continue;

            // Check ordering constraints
            let orderValid = true;
            for (const pattern of rule.patterns) {
                if (pattern.after !== undefined) {
                    const currentMatches = patternMatches.get(pattern.label);
                    const afterMatches = patternMatches.get(pattern.after);
                    if (currentMatches === undefined || afterMatches === undefined) {
                        orderValid = false;
                        break;
                    }

                    const earliestCurrent = Math.min(...currentMatches.map(e => e.tick));
                    const latestAfter = Math.max(...afterMatches.map(e => e.tick));
                    if (earliestCurrent <= latestAfter) {
                        orderValid = false;
                        break;
                    }
                }
            }

            if (!orderValid) continue;

            // Collect all evidence
            const evidence: SIEMLogEntry[] = [];
            for (const [, entries] of patternMatches) {
                evidence.push(...entries.slice(0, 3));
            }

            const alert: SIEMAlert = {
                id: `alert-${nextAlertId++}`,
                ruleId: rule.id,
                ruleName: rule.name,
                severity: rule.severity,
                timestamp: Date.now(),
                tick: currentTick,
                description: rule.description,
                evidence: Object.freeze(evidence),
                ...(rule.mitreTechnique !== undefined ? { mitreTechnique: rule.mitreTechnique } : {}),
                acknowledged: false,
                notes: '',
                falsePositive: false,
            };

            newAlerts.push(alert);
            alerts.push(alert);

            if (rule.cooldownTicks > 0) {
                ruleCooldowns.set(rule.id, currentTick + rule.cooldownTicks);
            }
        }

        return newAlerts;
    }

    function matchesQuery(entry: SIEMLogEntry, filter: SIEMQuery): boolean {
        if (filter.source !== undefined) {
            if (filter.source.machine !== undefined && entry.source.machine !== filter.source.machine) return false;
            if (filter.source.service !== undefined && entry.source.service !== filter.source.service) return false;
            if (filter.source.logFile !== undefined && entry.source.logFile !== filter.source.logFile) return false;
        }
        if (filter.severity !== undefined && !severityGte(entry.severity, filter.severity)) return false;
        if (filter.fromTick !== undefined && entry.tick < filter.fromTick) return false;
        if (filter.toTick !== undefined && entry.tick > filter.toTick) return false;
        if (filter.category !== undefined && entry.category !== filter.category) return false;
        if (filter.messageContains !== undefined && !entry.message.includes(filter.messageContains)) return false;
        if (filter.fieldEquals !== undefined) {
            for (const [key, value] of Object.entries(filter.fieldEquals)) {
                if (entry.fields[key] !== value) return false;
            }
        }
        if (filter.tags !== undefined) {
            for (const tag of filter.tags) {
                if (!entry.tags.includes(tag)) return false;
            }
        }
        return true;
    }

    return {
        ingest(entry: SIEMLogEntry): void {
            if (logs.length >= maxLogSize) {
                logs.splice(0, Math.floor(maxLogSize * 0.1)); // Evict oldest 10%
            }
            logs.push(entry);
        },

        ingestBatch(entries: readonly SIEMLogEntry[]): void {
            for (const entry of entries) {
                if (logs.length >= maxLogSize) {
                    logs.splice(0, Math.floor(maxLogSize * 0.1));
                }
                logs.push(entry);
            }
        },

        tick(tick: number): readonly SIEMAlert[] {
            currentTick = tick;
            const newAlerts: SIEMAlert[] = [];
            newAlerts.push(...evaluateDetectionRules(logs));
            newAlerts.push(...evaluateCorrelationRules());
            return Object.freeze(newAlerts);
        },

        query(filter: SIEMQuery): readonly SIEMLogEntry[] {
            const results: SIEMLogEntry[] = [];
            const limit = filter.limit ?? 1000;

            // Search from most recent
            for (let i = logs.length - 1; i >= 0 && results.length < limit; i--) {
                const entry = logs[i];
                if (entry !== undefined && matchesQuery(entry, filter)) {
                    results.push(entry);
                }
            }

            return Object.freeze(results);
        },

        getAlerts(): readonly SIEMAlert[] {
            return Object.freeze([...alerts]);
        },

        getPendingAlerts(): readonly SIEMAlert[] {
            return Object.freeze(alerts.filter(a => !a.acknowledged && !a.falsePositive));
        },

        acknowledgeAlert(alertId: string): boolean {
            const idx = alerts.findIndex(a => a.id === alertId);
            if (idx === -1) return false;
            const existing = alerts[idx];
            if (existing === undefined) return false;
            alerts[idx] = { ...existing, acknowledged: true };
            return true;
        },

        markFalsePositive(alertId: string): boolean {
            const idx = alerts.findIndex(a => a.id === alertId);
            if (idx === -1) return false;
            const existing = alerts[idx];
            if (existing === undefined) return false;
            alerts[idx] = { ...existing, falsePositive: true };
            return true;
        },

        addAlertNote(alertId: string, note: string): boolean {
            const idx = alerts.findIndex(a => a.id === alertId);
            if (idx === -1) return false;
            const existing = alerts[idx];
            if (existing === undefined) return false;
            const existingNotes = existing.notes;
            const newNotes = existingNotes !== '' ? existingNotes + '\n' + note : note;
            alerts[idx] = { ...existing, notes: newNotes };
            return true;
        },

        addRule(rule: SIEMDetectionRule): void {
            // Don't allow duplicate IDs
            if (detectionRules.some(r => r.id === rule.id)) {
                throw new Error(`SIEM: detection rule '${rule.id}' already exists`);
            }
            detectionRules.push(rule);
        },

        removeRule(ruleId: string): boolean {
            const idx = detectionRules.findIndex(r => r.id === ruleId);
            if (idx === -1) return false;
            detectionRules.splice(idx, 1);
            return true;
        },

        addCorrelationRule(rule: SIEMCorrelationRule): void {
            if (correlationRules.some(r => r.id === rule.id)) {
                throw new Error(`SIEM: correlation rule '${rule.id}' already exists`);
            }
            correlationRules.push(rule);
        },

        getRules(): readonly SIEMDetectionRule[] {
            return Object.freeze([...detectionRules]);
        },

        getCorrelationRules(): readonly SIEMCorrelationRule[] {
            return Object.freeze([...correlationRules]);
        },

        getStats(): SIEMStats {
            const bySeverity: Record<SIEMSeverity, number> = {
                debug: 0, info: 0, notice: 0, warning: 0,
                error: 0, critical: 0, alert: 0, emergency: 0,
            };
            const byMachine: Record<string, number> = {};
            const byService: Record<string, number> = {};

            for (const entry of logs) {
                bySeverity[entry.severity]++;
                byMachine[entry.source.machine] = (byMachine[entry.source.machine] ?? 0) + 1;
                byService[entry.source.service] = (byService[entry.source.service] ?? 0) + 1;
            }

            return {
                totalLogs: logs.length,
                totalAlerts: alerts.length,
                pendingAlerts: alerts.filter(a => !a.acknowledged && !a.falsePositive).length,
                bySeverity: Object.freeze(bySeverity),
                byMachine: Object.freeze(byMachine),
                byService: Object.freeze(byService),
                rulesActive: detectionRules.filter(r => r.enabled).length,
                correlationRulesActive: correlationRules.filter(r => r.enabled).length,
            };
        },

        timeline(fromTick: number, toTick: number): readonly SIEMLogEntry[] {
            return Object.freeze(
                logs.filter(e => e.tick >= fromTick && e.tick <= toTick)
                    .sort((a, b) => a.tick - b.tick || a.timestamp - b.timestamp),
            );
        },

        logCount(): number {
            return logs.length;
        },

        export(format: 'json' | 'cef' | 'csv'): string {
            switch (format) {
                case 'json':
                    return JSON.stringify(logs, null, 2);
                case 'cef':
                    return logs.map(e =>
                        `CEF:0|VARIANT|SIEM|1.0|${e.category}|${e.message}|${SEVERITY_ORDER[e.severity]}|src=${e.source.machine} svc=${e.source.service}`,
                    ).join('\n');
                case 'csv': {
                    const header = 'timestamp,tick,machine,service,severity,category,message';
                    const rows = logs.map(e =>
                        `${e.timestamp},${e.tick},${e.source.machine},${e.source.service},${e.severity},${e.category},"${e.message.replace(/"/g, '""')}"`,
                    );
                    return [header, ...rows].join('\n');
                }
            }
        },
    };
}

// ── Built-in Detection Rules ───────────────────────────────────

/**
 * Create standard detection rules for common attack patterns.
 * Level designers can add more via WorldSpec dynamics.
 */
export function createBuiltinDetectionRules(): readonly SIEMDetectionRule[] {
    return Object.freeze([
        {
            id: 'brute-force-ssh',
            name: 'SSH Brute Force Detected',
            description: 'Multiple failed SSH login attempts from the same source',
            severity: 'warning' as const,
            mitreTechnique: 'T1110.001',
            conditions: [
                { type: 'category-equals' as const, category: 'auth' },
                { type: 'message-contains' as const, substring: 'Failed password' },
            ],
            threshold: 5,
            windowTicks: 30,
            cooldownTicks: 60,
            enabled: true,
        },
        {
            id: 'privilege-escalation',
            name: 'Privilege Escalation Attempt',
            description: 'sudo or su usage detected',
            severity: 'warning' as const,
            mitreTechnique: 'T1548',
            conditions: [
                { type: 'category-equals' as const, category: 'auth' },
                { type: 'message-regex' as const, pattern: '(sudo|su).*command' },
            ],
            threshold: 1,
            windowTicks: 1,
            cooldownTicks: 10,
            enabled: true,
        },
        {
            id: 'web-shell-detected',
            name: 'Web Shell Activity',
            description: 'HTTP request to a suspicious file extension',
            severity: 'critical' as const,
            mitreTechnique: 'T1505.003',
            conditions: [
                { type: 'source-service' as const, service: 'http' },
                { type: 'message-regex' as const, pattern: '\\.(php|jsp|asp|aspx|sh|py|pl)\\?cmd=' },
            ],
            threshold: 1,
            windowTicks: 1,
            cooldownTicks: 30,
            enabled: true,
        },
        {
            id: 'port-scan',
            name: 'Port Scan Detected',
            description: 'Connection attempts to multiple ports from the same source',
            severity: 'info' as const,
            mitreTechnique: 'T1046',
            conditions: [
                { type: 'category-equals' as const, category: 'network' },
                { type: 'message-contains' as const, substring: 'connection refused' },
            ],
            threshold: 10,
            windowTicks: 10,
            cooldownTicks: 30,
            enabled: true,
        },
        {
            id: 'data-exfiltration',
            name: 'Possible Data Exfiltration',
            description: 'Large outbound data transfer detected',
            severity: 'alert' as const,
            mitreTechnique: 'T1041',
            conditions: [
                { type: 'category-equals' as const, category: 'network' },
                { type: 'tag-present' as const, tag: 'outbound' },
                { type: 'tag-present' as const, tag: 'large-transfer' },
            ],
            threshold: 1,
            windowTicks: 1,
            cooldownTicks: 60,
            enabled: true,
        },
        {
            id: 'sql-injection',
            name: 'SQL Injection Attempt',
            description: 'HTTP request with SQL injection pattern',
            severity: 'critical' as const,
            mitreTechnique: 'T1190',
            conditions: [
                { type: 'source-service' as const, service: 'http' },
                { type: 'message-regex' as const, pattern: "('|\"|--).*((union|select|insert|update|delete|drop|alter|exec|execute|xp_))" },
            ],
            threshold: 1,
            windowTicks: 1,
            cooldownTicks: 5,
            enabled: true,
        },
    ]);
}

/**
 * Create standard correlation rules for multi-stage attacks.
 */
export function createBuiltinCorrelationRules(): readonly SIEMCorrelationRule[] {
    return Object.freeze([
        {
            id: 'recon-to-exploit',
            name: 'Reconnaissance Followed by Exploitation',
            description: 'Port scanning followed by service exploitation from the same source',
            severity: 'critical' as const,
            mitreTechnique: 'TA0001',
            patterns: [
                {
                    label: 'recon',
                    conditions: [
                        { type: 'category-equals' as const, category: 'network' },
                        { type: 'message-contains' as const, substring: 'scan' },
                    ],
                },
                {
                    label: 'exploit',
                    conditions: [
                        { type: 'severity-gte' as const, minSeverity: 'warning' as const },
                        { type: 'category-equals' as const, category: 'auth' },
                    ],
                    after: 'recon',
                },
            ],
            windowTicks: 120,
            cooldownTicks: 120,
            enabled: true,
        },
        {
            id: 'credential-theft-lateral',
            name: 'Credential Theft Then Lateral Movement',
            description: 'Credential found event followed by SSH login to another machine',
            severity: 'critical' as const,
            mitreTechnique: 'T1021.004',
            patterns: [
                {
                    label: 'cred-found',
                    conditions: [
                        { type: 'category-equals' as const, category: 'credential' },
                        { type: 'message-contains' as const, substring: 'found' },
                    ],
                },
                {
                    label: 'lateral',
                    conditions: [
                        { type: 'category-equals' as const, category: 'auth' },
                        { type: 'message-contains' as const, substring: 'Accepted' },
                    ],
                    after: 'cred-found',
                },
            ],
            windowTicks: 200,
            cooldownTicks: 200,
            enabled: true,
        },
    ]);
}
